### PR TITLE
Re nest parallelize

### PR DESCRIPTION
**Pull request by Oddant1**
Re nest the pipelines so things will parallelize

### CODE REVIEW

**Comment by Oddant1** [comment]
blocked by qiime2/qiime2#790

**Comment by colinbrislawn** [comment]
Looks like this plugin is _slower_ when adding `--parallel`!

Is this PR related or should I open a new issue?

**Comment by Oddant1** [comment]
@ebolyen and @gregcaporaso now that qiime2/qiime2#790 is merged this ought to work as intended

**Comment by gregcaporaso** [comment]
@Oddant1, fyi I rebased to test with the most recent environment files - that's what the force-commits are, in case you're wondering.

**Review by gregcaporaso — APPROVED** [review]
All changes look right, thanks @Oddant1! Just doing some local testing of serial v parallel runs - if all good there, this is ready for merge.

**Pull request merged**
